CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE email_confirmacao (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    num_codigo text NOT NULL,
    boo_confirmado boolean NOT NULL,
    ref_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_email_confirmacao" PRIMARY KEY ("Id")
);

CREATE TABLE moderador (
    moderador_id integer GENERATED BY DEFAULT AS IDENTITY,
    senha text NOT NULL,
    nome text NOT NULL,
    email text NOT NULL,
    CONSTRAINT "PK_moderador" PRIMARY KEY (moderador_id)
);

CREATE TABLE notificacao (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    mensagem text NOT NULL,
    boo_lida boolean NOT NULL,
    ref_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_notificacao" PRIMARY KEY ("Id")
);

CREATE TABLE questionario (
    questionario_id integer GENERATED BY DEFAULT AS IDENTITY,
    num_resultado integer NOT NULL,
    dsc_resultado text,
    boo_avaliado boolean NOT NULL,
    boo_excluido boolean NOT NULL,
    CONSTRAINT "PK_questionario" PRIMARY KEY (questionario_id)
);

CREATE TABLE empresa (
    "Cnpj" text NOT NULL,
    senha text NOT NULL,
    email text NOT NULL,
    razao_social text NOT NULL,
    num_telefone text NOT NULL,
    endereco_sede text NOT NULL,
    foto_perfil bytea,
    dsc_empresa text,
    setor_atuacao text NOT NULL,
    boo_email_confirmado boolean NOT NULL,
    boo_removida boolean NOT NULL,
    "ModeradorId" integer,
    CONSTRAINT "PK_empresa" PRIMARY KEY ("Cnpj"),
    CONSTRAINT "FK_empresa_moderador_ModeradorId" FOREIGN KEY ("ModeradorId") REFERENCES moderador (moderador_id)
);

CREATE TABLE questao (
    questao_id integer GENERATED BY DEFAULT AS IDENTITY,
    tipo_questao integer NOT NULL,
    pergunta text NOT NULL,
    "QuestionarioId" integer,
    CONSTRAINT "PK_questao" PRIMARY KEY (questao_id),
    CONSTRAINT "FK_questao_questionario_QuestionarioId" FOREIGN KEY ("QuestionarioId") REFERENCES questionario (questionario_id)
);

CREATE TABLE "EmpresaQuestionario" (
    "EmpresasCnpj" text NOT NULL,
    "QuestionariosId" integer NOT NULL,
    CONSTRAINT "PK_EmpresaQuestionario" PRIMARY KEY ("EmpresasCnpj", "QuestionariosId"),
    CONSTRAINT "FK_EmpresaQuestionario_empresa_EmpresasCnpj" FOREIGN KEY ("EmpresasCnpj") REFERENCES empresa ("Cnpj") ON DELETE CASCADE,
    CONSTRAINT "FK_EmpresaQuestionario_questionario_QuestionariosId" FOREIGN KEY ("QuestionariosId") REFERENCES questionario (questionario_id) ON DELETE CASCADE
);

CREATE TABLE relatorio (
    relatorio_id integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpresaCnpj" text,
    dsc_sustentabilidade text NOT NULL,
    dsc_melhorias text NOT NULL,
    boo_revisado boolean NOT NULL,
    "RevisorId" integer,
    CONSTRAINT "PK_relatorio" PRIMARY KEY (relatorio_id),
    CONSTRAINT "FK_relatorio_empresa_EmpresaCnpj" FOREIGN KEY ("EmpresaCnpj") REFERENCES empresa ("Cnpj"),
    CONSTRAINT "FK_relatorio_moderador_RevisorId" FOREIGN KEY ("RevisorId") REFERENCES moderador (moderador_id)
);

CREATE INDEX "IX_empresa_ModeradorId" ON empresa ("ModeradorId");

CREATE INDEX "IX_EmpresaQuestionario_QuestionariosId" ON "EmpresaQuestionario" ("QuestionariosId");

CREATE INDEX "IX_questao_QuestionarioId" ON questao ("QuestionarioId");

CREATE INDEX "IX_relatorio_EmpresaCnpj" ON relatorio ("EmpresaCnpj");

CREATE INDEX "IX_relatorio_RevisorId" ON relatorio ("RevisorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250331003354_fix', '9.0.3');

COMMIT;

